# Generated by Django 5.2.1 on 2025-07-04 07:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 4, 7, 3, 2, 400859, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
